FROM ubuntu:latest
LABEL name="bala"
ENV AWS_ACCESS_KEY_ID=12345
ENV AWS_SECRET_KEY_ID=12345
ENV AWS_DEFAULT_REGION=US-EAST-1B
ARG T_VERSION='1.6.6'
ARG P_VERSION='1.8.0'
RUN apt update && apt install -y jq net-tools curl wget unzip && apt install -y nginx iputils-ping
#RUN wget https://releases.hashicorp.com/packer/${P_VERSION}/packer_${P_VERSION}_linux_amd64.zip && wget https://releases.hashicorp.com/terraform/${T_VERSION}/terraform_${T_VERSION}_linux_amd64.zip && unzip terraform_${T_VERSION}_linux_amd64.zip && unzip packer_${P_VERSION}_linux_amd64.zip && chmod 777 terraform && chmod 777 packer && ./terraform version && ./packer version
EXPOSE 80
CMD ["nginx","-g","daemon off;"]