apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: testpod1
  name: testpod1
  annotations:
    info: "bala deployment"
    email: "bala"
    owner: "bala"
spec:
  replicas: 6
  selector:
    matchLabels:
      app: testpod1
  strategy: {}
  template:
    metadata:
      labels:
        app: testpod1
    spec:
      containers:
        - image: kiran2361993/kubegame:v2
          name: kubegame
        - image: kiran2361993/mydb:v1
          name: mysqldb
          env:
            - name: DB_NAME
              value: "mysqldb"
            - name: DB_PORT
              value: "3306"
            - name: DB_URL
              value: "www"