apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp01
  name: myapp01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp01
  template:
    metadata:
      labels:
        app: myapp01
    spec:
      containers:
        - image: balatuluva/kubegame:v1
          name: kubegame
      nodeSelector:
        kubernetes.io/hostname: i-044ed660f5d4c3e34

#kubectl get pods -o wide --no-headers |  awk -F"  " '{print $1 $8}'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp02
  name: myapp02
spec:
  replicas: 4
  selector:
    matchLabels:
      app: myapp02
  template:
    metadata:
      labels:
        app: myapp02
    spec:
      containers:
        - image: balatuluva/kubegame:v1
          name: kubegame
      nodeSelector:
        high-perf-cpu: "yes"

---

kubectl label node i-044ed660f5d4c3e34 high-perf-cpu=yes
kubectl label node i-0fb062b8a981a9da0 low-perf-cpu=yes